export const ACCENT_COLOR = {
    variable: '--accent-color',
    light: '#1b73fb',
    dark: '#4e93ff',
};

export const CATEGORY_COLORS = {
    1: {
        id: 1,
        name: 'Green',
        variable: '--category-color-1',
        className: 'category_color_1',
        light: '#007e2b',
        dark: '#00ff56',
    },
    2: {
        id: 2,
        name: 'Yellow',
        variable: '--category-color-2',
        className: 'category_color_2',
        light: '#d99600',
        dark: '#ffc219',
    },
    3: {
        id: 3,
        name: 'Blue',
        variable: '--category-color-3',
        className: 'category_color_3',
        light: '#0047c4',
        dark: '#0f66ff',
    },
    4: {
        id: 4,
        name: 'Purple',
        variable: '--category-color-4',
        className: 'category_color_4',
        light: '#7a00ff',
        dark: '#7a00ff',
    },
    5: {
        id: 5,
        name: 'Red',
        variable: '--category-color-5',
        className: 'category_color_5',
        light: '#ff0000',
        dark: '#ff5b5b',
    },
    6: {
        id: 6,
        name: 'Sky blue',
        variable: '--category-color-6',
        className: 'category_color_6',
        light: '#00b2ff',
        dark: '#00bdff',
    },
    7: {
        id: 7,
        name: 'Teal',
        variable: '--category-color-7',
        className: 'category_color_7',
        light: '#00c0aa',
        dark: '#00ffe1',
    },
    8: {
        id: 8,
        name: 'Pink',
        variable: '--category-color-8',
        className: 'category_color_8',
        light: '#ff00c4',
        dark: '#ff178b',
    },
    9: {
        id: 9,
        name: 'Orange',
        variable: '--category-color-9',
        className: 'category_color_9',
        light: '#ff6800',
        dark: '#ff6a3d',
    },
    10: {
        id: 10,
        name: 'Lime',
        variable: '--category-color-10',
        className: 'category_color_10',
        light: '#83ad00',
        dark: '#afd100',
    },
} as any;
